name = ctf_gamemode_vote
description = Adds an inventory "Vote" tab where players can vote to switch the CTF gamemode. If 2/3 of online players vote for the same mode, it is forcefully switched.
depends = ctf_modebase, ctf_api, sfinv
